a := one two# a é associado à string "one two"
b := 'one two'# b é associado à string "'one two'"

all: small
	printf '$a'
	printf $b


# Estamos simplesmente manipulando strings
x := dude
small:
	echo $(x)
	echo ${x}
	#bad practice but works
	echo $x
