# Podemos aninhar diferentes alvos em all
# e como ele é o default, irá rodar sempre

files:=one two three

all: one two three

one:
	touch one

two:
	touch two

three:
	touch three

clean:
	rm $(files)
