# O make nada mais faz do que executar alguns
# comandos em ordem, de forna automatizada. Temos
# como funcionalidades chave:
# A capacidade de criar ações específicas no
# projeto como make clean.
# A capacidade de recompilar apenas os arquivos
# necessários, visto que ele analisa a hierarquia
# do "build process".
# A capacidade de, genericamente, lidar com
# quantidades de arquivos diferentes no momento
# de compilar. Apenas dê a lista de arquivos
# fonte e veja a mágica acontecer. De resto, é
# basicamente shellscript nas entranhas.
hello:
	echo "Hello World!!"
